---

name: ramius
on:
  workflow_dispatch:

jobs:

  job_setup:
    runs-on: ubuntu-latest
    steps:
      - name: retrieve ${{ github.event.repository.name }} project
        uses: actions/checkout@v5

      - id: semver_tag
        name: retrieve semantic version of latest tag
        run: |
          read -r semver_tag <<< $(./utils/equate_tag_semver "library/almalinux:latest")
          test -n ${semver_tag} || exit 1
          echo "semver_tag=${semver_tag}" >> $GITHUB_OUTPUT
    outputs:
      semver_tag: ${{ steps.semver_tag.outputs.semver_tag }}

  job_docker:
    runs-on: ubuntu-latest
    needs: [ job_setup ]
    steps:
      - name: retrieve ${{ github.event.repository.name }} project
        uses: actions/checkout@v5

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push - mantid development image
        uses: docker/build-push-action@v6
        with:
          context:  Linux/development/docker
          file:     Linux/development/docker/Alma9.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mantid-development-alma:${{ needs.job_setup.outputs.semver_tag }}
          build-args: |
            SEMVER_TAG=${{ needs.job_setup.outputs.semver_tag }}


